[promise.py]
  [test_await_promise_resolve]
    bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1527713
    expected: FAIL
